import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import { SearchProvider } from "./context/SearchContext";
import { BooksProvider } from "./context/BooksContext";
import {ThemeProvider} from "./components/ThemeProvider";
import { FavoritesProvider } from "./context/FavoritesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <BooksProvider>
            <SearchProvider>
              <FavoritesProvider>
                <Header />
                <main className="pt-4">{children}</main>
              </FavoritesProvider>
            </SearchProvider>
          </BooksProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
